// Autogenerated from Pigeon (v21.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class PigeonCryptoCapabilities {
  PigeonCryptoCapabilities({
    required this.supportsSecureEnclave,
    required this.supportsStrongBox,
    required this.supportsHardwareKeys,
    required this.supportsBiometrics,
    required this.supportsAttestation,
    required this.supportsKeyWrapping,
  });

  bool supportsSecureEnclave;
  bool supportsStrongBox;
  bool supportsHardwareKeys;
  bool supportsBiometrics;
  bool supportsAttestation;
  bool supportsKeyWrapping;

  Object encode() {
    return <Object?>[
      supportsSecureEnclave,
      supportsStrongBox,
      supportsHardwareKeys,
      supportsBiometrics,
      supportsAttestation,
      supportsKeyWrapping,
    ];
  }

  static PigeonCryptoCapabilities decode(Object result) {
    result as List<Object?>;
    return PigeonCryptoCapabilities(
      supportsSecureEnclave: result[0]! as bool,
      supportsStrongBox: result[1]! as bool,
      supportsHardwareKeys: result[2]! as bool,
      supportsBiometrics: result[3]! as bool,
      supportsAttestation: result[4]! as bool,
      supportsKeyWrapping: result[5]! as bool,
    );
  }
}

class PigeonKeyMetadata {
  PigeonKeyMetadata({
    required this.keyId,
    required this.isHardwareBacked,
    required this.algorithm,
  });

  String keyId;
  bool isHardwareBacked;
  String algorithm;

  Object encode() {
    return <Object?>[
      keyId,
      isHardwareBacked,
      algorithm,
    ];
  }

  static PigeonKeyMetadata decode(Object result) {
    result as List<Object?>;
    return PigeonKeyMetadata(
      keyId: result[0]! as String,
      isHardwareBacked: result[1]! as bool,
      algorithm: result[2]! as String,
    );
  }
}

class _NativeCryptoApiCodec extends StandardMessageCodec {
  const _NativeCryptoApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is PigeonCryptoCapabilities) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is PigeonKeyMetadata) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return PigeonCryptoCapabilities.decode(readValue(buffer)!);
      case 129: 
        return PigeonKeyMetadata.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class NativeCryptoApi {
  /// Constructor for [NativeCryptoApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NativeCryptoApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : __pigeon_binaryMessenger = binaryMessenger,
        __pigeon_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _NativeCryptoApiCodec();

  final String __pigeon_messageChannelSuffix;

  Future<PigeonCryptoCapabilities> getCapabilities() async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.lifecircle_mobile.NativeCryptoApi.getCapabilities$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as PigeonCryptoCapabilities?)!;
    }
  }

  Future<PigeonKeyMetadata> generateKey(String keyId, bool requireHardware, bool requireBiometrics) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.lifecircle_mobile.NativeCryptoApi.generateKey$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[keyId, requireHardware, requireBiometrics]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as PigeonKeyMetadata?)!;
    }
  }

  Future<void> destroyKey(String keyId) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.lifecircle_mobile.NativeCryptoApi.destroyKey$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[keyId]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<Uint8List> signPayload(String keyId, Uint8List payload) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.lifecircle_mobile.NativeCryptoApi.signPayload$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[keyId, payload]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as Uint8List?)!;
    }
  }

  Future<Uint8List> unwrapKey(String keyId, Uint8List wrappedKey) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.lifecircle_mobile.NativeCryptoApi.unwrapKey$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[keyId, wrappedKey]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as Uint8List?)!;
    }
  }

  Future<Uint8List> requestAttestation(String keyId, Uint8List challenge) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.lifecircle_mobile.NativeCryptoApi.requestAttestation$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[keyId, challenge]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as Uint8List?)!;
    }
  }
}
