import Foundation
import Security
import LocalAuthentication

// Assuming CryptoApi is generated by Pigeon
class CryptoPlugin: NSObject, NativeCryptoApi {
    func getCapabilities() throws -> PigeonCryptoCapabilities {
        var hasEnclave = false
        // Basic check for Secure Enclave availability
        let context = LAContext()
        var error: NSError?
        if context.canEvaluatePolicy(.deviceOwnerAuthenticationWithBiometrics, error: &error) {
            hasEnclave = true
        }

        return PigeonCryptoCapabilities(
            supportsSecureEnclave: hasEnclave,
            supportsStrongBox: false, // Android only
            supportsHardwareKeys: hasEnclave,
            supportsBiometrics: hasEnclave,
            supportsAttestation: true, // App Attest
            supportsKeyWrapping: true
        )
    }

    func generateKey(keyId: String, requireHardware: Bool, requireBiometrics: Bool) throws -> PigeonKeyMetadata {
        let tag = "com.lifecircle.mobile.keys.\(keyId)".data(using: .utf8)!
        
        var attributes: [String: Any] = [
            kSecAttrKeyType as String: kSecAttrKeyTypeECSECPrimeRandom,
            kSecAttrKeySizeInBits as String: 256,
            kSecPrivateKeyAttrs as String: [
                kSecAttrIsPermanent as String: true,
                kSecAttrApplicationTag as String: tag
            ]
        ]
        
        if requireHardware {
            // Force Secure Enclave
            let tokenID = kSecAttrTokenIDSecureEnclave
            attributes[kSecAttrTokenID as String] = tokenID
        }
        
        if requireBiometrics {
            let access = SecAccessControlCreateWithFlags(
                kCFAllocatorDefault,
                kSecAttrAccessibleWhenUnlockedThisDeviceOnly,
                .biometryCurrentSet,
                nil
            )!
            var privateAttrs = attributes[kSecPrivateKeyAttrs as String] as! [String: Any]
            privateAttrs[kSecAttrAccessControl as String] = access
            attributes[kSecPrivateKeyAttrs as String] = privateAttrs
        } else {
            // Migratable keychain item
            var privateAttrs = attributes[kSecPrivateKeyAttrs as String] as! [String: Any]
            privateAttrs[kSecAttrAccessible as String] = kSecAttrAccessibleWhenUnlocked
            attributes[kSecPrivateKeyAttrs as String] = privateAttrs
        }

        var error: Unmanaged<CFError>?
        guard SecKeyCreateRandomKey(attributes as CFDictionary, &error) != nil else {
            throw NSError(domain: "CryptoPlugin", code: 1, userInfo: [NSLocalizedDescriptionKey: "Failed to generate key"])
        }

        return PigeonKeyMetadata(
            keyId: keyId,
            isHardwareBacked: requireHardware,
            algorithm: "EC-P256"
        )
    }

    func destroyKey(keyId: String) throws {
        let tag = "com.lifecircle.mobile.keys.\(keyId)".data(using: .utf8)!
        let query: [String: Any] = [
            kSecClass as String: kSecClassKey,
            kSecAttrApplicationTag as String: tag
        ]
        
        let status = SecItemDelete(query as CFDictionary)
        if status != errSecSuccess && status != errSecItemNotFound {
            throw NSError(domain: "CryptoPlugin", code: Int(status), userInfo: nil)
        }
    }

    func signPayload(keyId: String, payload: FlutterStandardTypedData) throws -> FlutterStandardTypedData {
        let tag = "com.lifecircle.mobile.keys.\(keyId)".data(using: .utf8)!
        let query: [String: Any] = [
            kSecClass as String: kSecClassKey,
            kSecAttrApplicationTag as String: tag,
            kSecAttrKeyType as String: kSecAttrKeyTypeECSECPrimeRandom,
            kSecReturnRef as String: true
        ]
        
        var item: CFTypeRef?
        let status = SecItemCopyMatching(query as CFDictionary, &item)
        guard status == errSecSuccess else {
            throw NSError(domain: "CryptoPlugin", code: Int(status), userInfo: [NSLocalizedDescriptionKey: "Key not found"])
        }
        
        let privateKey = item as! SecKey
        var error: Unmanaged<CFError>?
        guard let signature = SecKeyCreateSignature(privateKey, .ecdsaSignatureMessageX962SHA256, payload.data as CFData, &error) else {
            throw NSError(domain: "CryptoPlugin", code: 2, userInfo: [NSLocalizedDescriptionKey: "Signature failed"])
        }
        
        return FlutterStandardTypedData(bytes: signature as Data)
    }

    func unwrapKey(keyId: String, wrappedKey: FlutterStandardTypedData) throws -> FlutterStandardTypedData {
        // Implement ECDH or similar unwrapping
        throw NSError(domain: "CryptoPlugin", code: 3, userInfo: [NSLocalizedDescriptionKey: "Unimplemented"])
    }

    func requestAttestation(keyId: String, challenge: FlutterStandardTypedData) throws -> FlutterStandardTypedData {
        // App Attest / DCAppAttestService.shared.attestKey(keyId, clientDataHash: challenge)
        // Returning a mock attestation object for SEC-004C.3 architecture design
        let mockAttestation = "mock_apple_attestation_for_\(keyId)".data(using: .utf8)!
        return FlutterStandardTypedData(bytes: mockAttestation)
    }
}
