name: lifecircle_os
publish_to: none

environment:
  sdk: ^3.12.0

dev_dependencies:
  melos: ^7.0.0

workspace:
  - apps/mobile
  - packages/shared

melos:
  packages:
    - apps/**
    - packages/**

  scripts:
    analyze:
      run: flutter analyze
      exec:
        concurrency: 1
        failFast: true

    test:
      run: flutter test
      exec:
        concurrency: 1
        failFast: true

    format:
      run: dart format .

    clean:
      run: flutter clean
