name: lifecircle_os
publish_to: none

environment:
  sdk: ^3.12.0

dev_dependencies:
  melos: ^7.0.0

workspace:
  - apps/mobile
  - packages/shared

melos:
  packages:
    - apps/**
    - packages/**

  scripts:
    analyze:
      run: melos exec -- flutter analyze

    test:
      run: melos exec -- flutter test

    format:
      run: melos exec -- dart format .

    clean:
      run: melos exec -- flutter clean
