// Mocks generated by Mockito 5.4.4 from annotations
// in lifecircle_mobile/test/unit/responsibilities/responsibility_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:lifecircle_mobile/src/core/utils/trusted_clock.dart' as _i5;
import 'package:lifecircle_mobile/src/features/responsibilities/domain/models/family_responsibility.dart'
    as _i4;
import 'package:lifecircle_mobile/src/features/responsibilities/infrastructure/repositories/responsibility_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ResponsibilityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockResponsibilityRepository extends _i1.Mock
    implements _i2.ResponsibilityRepository {
  MockResponsibilityRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveResponsibility(
          _i4.FamilyResponsibility? responsibility) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveResponsibility,
          [responsibility],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.FamilyResponsibility?> getResponsibilityByUuid(String? uuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getResponsibilityByUuid,
          [uuid],
        ),
        returnValue: _i3.Future<_i4.FamilyResponsibility?>.value(),
      ) as _i3.Future<_i4.FamilyResponsibility?>);

  @override
  _i3.Future<List<_i4.FamilyResponsibility>> getAllResponsibilities() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllResponsibilities,
          [],
        ),
        returnValue: _i3.Future<List<_i4.FamilyResponsibility>>.value(
            <_i4.FamilyResponsibility>[]),
      ) as _i3.Future<List<_i4.FamilyResponsibility>>);

  @override
  _i3.Future<void> deleteResponsibility(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #deleteResponsibility,
          [uuid],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.FamilyResponsibility>> getResponsibilitiesForOwner(
          String? ownerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getResponsibilitiesForOwner,
          [ownerId],
        ),
        returnValue: _i3.Future<List<_i4.FamilyResponsibility>>.value(
            <_i4.FamilyResponsibility>[]),
      ) as _i3.Future<List<_i4.FamilyResponsibility>>);
}

/// A class which mocks [TrustedClock].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrustedClock extends _i1.Mock implements _i5.TrustedClock {
  MockTrustedClock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  DateTime now() => (super.noSuchMethod(
        Invocation.method(
          #now,
          [],
        ),
        returnValue: _FakeDateTime_0(
          this,
          Invocation.method(
            #now,
            [],
          ),
        ),
      ) as DateTime);
}
