"""phase_3_2_invitations_and_dynamic_rbac

Revision ID: 627298ed5661
Revises: phase_2_2_organizations
Create Date: 2026-07-01 22:53:29.708681

"""

from collections.abc import Sequence
from datetime import UTC

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "627298ed5661"
down_revision: str | None = "phase_2_2_organizations"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_event_type"), "audit_logs", ["event_type"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("is_system_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_roles_org_name"),
    )
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=False)
    op.create_index(op.f("ix_roles_organization_id"), "roles", ["organization_id"], unique=False)
    op.create_index(
        "uq_roles_global_name",
        "roles",
        ["name"],
        unique=True,
        postgresql_where=sa.text("organization_id IS NULL"),
    )
    op.create_table(
        "organization_invitations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("inviter_id", sa.UUID(), nullable=True),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("PENDING", "ACCEPTED", "EXPIRED", "REVOKED", name="invitation_state"),
            nullable=False,
        ),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["inviter_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_invitations_email"),
        "organization_invitations",
        ["email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_invitations_organization_id"),
        "organization_invitations",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_invitations_state"),
        "organization_invitations",
        ["state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_invitations_token_hash"),
        "organization_invitations",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        "uq_org_email_pending",
        "organization_invitations",
        ["organization_id", "email"],
        unique=True,
        postgresql_where=sa.text("state = 'PENDING'"),
    )
    op.create_table(
        "role_permissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column(
            "permission",
            sa.Enum(
                "ORGANIZATION_READ",
                "ORGANIZATION_UPDATE",
                "ORGANIZATION_DELETE",
                "MEMBERS_READ",
                "MEMBERS_INVITE",
                "MEMBERS_UPDATE",
                "MEMBERS_REMOVE",
                "BILLING_READ",
                "BILLING_MANAGE",
                "PROFILE_MANAGE",
                name="permission_type",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_id", "permission", name="uq_role_permission"),
    )
    op.create_index(
        op.f("ix_role_permissions_permission"), "role_permissions", ["permission"], unique=False
    )
    op.create_index(
        op.f("ix_role_permissions_role_id"), "role_permissions", ["role_id"], unique=False
    )
    op.add_column("organization_members", sa.Column("role_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_org_members_roles",
        "organization_members",
        "roles",
        ["role_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # --- DATA MIGRATION ---
    import uuid
    from datetime import datetime

    bind = op.get_bind()

    owner_id = "00000000-0000-0000-0000-000000000001"
    admin_id = "00000000-0000-0000-0000-000000000002"
    member_id = "00000000-0000-0000-0000-000000000003"
    viewer_id = "00000000-0000-0000-0000-000000000004"
    now = datetime.now(UTC)

    bind.execute(
        sa.text("""
        INSERT INTO roles (id, name, description, is_system_default, created_at, updated_at)
        VALUES
        (:owner_id, 'Owner', 'Organization Owner', true, :now, :now),
        (:admin_id, 'Admin', 'Organization Administrator', true, :now, :now),
        (:member_id, 'Member', 'Organization Member', true, :now, :now),
        (:viewer_id, 'Viewer', 'Organization Viewer', true, :now, :now)
        """).bindparams(
            owner_id=owner_id, admin_id=admin_id, member_id=member_id, viewer_id=viewer_id, now=now
        )
    )

    # Insert default role_permissions
    permissions = [
        # Owner gets everything
        (owner_id, "ORGANIZATION_READ"),
        (owner_id, "ORGANIZATION_UPDATE"),
        (owner_id, "ORGANIZATION_DELETE"),
        (owner_id, "MEMBERS_READ"),
        (owner_id, "MEMBERS_INVITE"),
        (owner_id, "MEMBERS_UPDATE"),
        (owner_id, "MEMBERS_REMOVE"),
        (owner_id, "BILLING_READ"),
        (owner_id, "BILLING_MANAGE"),
        (owner_id, "PROFILE_MANAGE"),
        # Admin gets most things
        (admin_id, "ORGANIZATION_READ"),
        (admin_id, "ORGANIZATION_UPDATE"),
        (admin_id, "MEMBERS_READ"),
        (admin_id, "MEMBERS_INVITE"),
        (admin_id, "MEMBERS_UPDATE"),
        (admin_id, "MEMBERS_REMOVE"),
        (admin_id, "BILLING_READ"),
        (admin_id, "PROFILE_MANAGE"),
        # Member gets read and basic profile management
        (member_id, "ORGANIZATION_READ"),
        (member_id, "MEMBERS_READ"),
        (member_id, "PROFILE_MANAGE"),
        # Viewer only reads
        (viewer_id, "ORGANIZATION_READ"),
        (viewer_id, "MEMBERS_READ"),
    ]

    for r_id, p in permissions:
        bind.execute(
            sa.text(
                "INSERT INTO role_permissions (id, role_id, permission) "
                "VALUES (:id, :role_id, :permission)"
            ).bindparams(id=uuid.uuid4(), role_id=r_id, permission=p)
        )

    bind.execute(
        sa.text("""
        UPDATE organization_members
        SET role_id = CASE
            WHEN role = 'owner' THEN :owner_id
            WHEN role = 'admin' THEN :admin_id
            WHEN role = 'member' THEN :member_id
            WHEN role = 'viewer' THEN :viewer_id
            ELSE :member_id
        END
        """).bindparams(
            owner_id=owner_id, admin_id=admin_id, member_id=member_id, viewer_id=viewer_id
        )
    )
    # ----------------------

    op.alter_column("organization_members", "role_id", nullable=False)
    op.drop_column("organization_members", "role")
    op.add_column("refresh_tokens", sa.Column("jti", sa.String(), nullable=True))
    op.add_column(
        "refresh_tokens", sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("refresh_tokens", sa.Column("device_info", sa.Text(), nullable=True))
    op.alter_column(
        "refresh_tokens",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(op.f("ix_refresh_tokens_jti"), "refresh_tokens", ["jti"], unique=False)
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "is_superuser", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("users", "is_superuser", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_index(op.f("ix_refresh_tokens_jti"), table_name="refresh_tokens")
    op.alter_column(
        "refresh_tokens",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("refresh_tokens", "device_info")
    op.drop_column("refresh_tokens", "revoked_at")
    op.drop_column("refresh_tokens", "jti")
    op.add_column(
        "organization_members",
        sa.Column("role", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    )

    # --- DOWNGRADE DATA MIGRATION ---
    bind = op.get_bind()
    bind.execute(
        sa.text("""
        UPDATE organization_members om
        SET role = (
            SELECT CASE
                WHEN LOWER(r.name) = 'viewer' THEN 'member'
                ELSE LOWER(r.name)
            END
            FROM roles r WHERE r.id = om.role_id
        )
        """)
    )
    op.alter_column("organization_members", "role", nullable=False)
    # --------------------------------

    op.drop_constraint("fk_org_members_roles", "organization_members", type_="foreignkey")
    op.drop_column("organization_members", "role_id")
    op.drop_index(op.f("ix_role_permissions_role_id"), table_name="role_permissions")
    op.drop_index(op.f("ix_role_permissions_permission"), table_name="role_permissions")
    op.drop_table("role_permissions")
    op.drop_index(
        op.f("ix_organization_invitations_token_hash"), table_name="organization_invitations"
    )
    op.drop_index(op.f("ix_organization_invitations_state"), table_name="organization_invitations")
    op.drop_index(
        op.f("ix_organization_invitations_organization_id"), table_name="organization_invitations"
    )
    op.drop_index(op.f("ix_organization_invitations_email"), table_name="organization_invitations")
    op.drop_table("organization_invitations")
    op.drop_index(op.f("ix_roles_organization_id"), table_name="roles")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_event_type"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
